// The Vue <SoneIcon> renders the same glyphs as the Angular <sone-icon>: this script
// reads the @switch in packages/angular/icon/icon.component.html (the one source of
// truth) and writes src/components/icon/icons.generated.ts — never edit that by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "../../angular/icon/icon.component.html");
const target = join(here, "../src/components/icon/icons.generated.ts");

const html = readFileSync(source, "utf8");
const icons = {};
const caseRe = /@case \("([^"]+)"\) \{\s*(<svg[\s\S]*?<\/svg>)\s*\}/g;
for (const [, name, svg] of html.matchAll(caseRe)) {
  if (/\[|\{\{|@if|@for/.test(svg)) {
    throw new Error(
      `icon "${name}" has an Angular binding; it cannot be copied`,
    );
  }
  icons[name] = svg.replace(/\s*\n\s*/g, " ").replace(/\s+\/>/g, "/>");
}

const names = Object.keys(icons);
if (names.length < 10) {
  throw new Error(`only ${names.length} icons found in ${source}`);
}

const out = `// GENERATED by scripts/generate-icons.mjs from packages/angular/icon — do not edit.
export const SONE_ICONS = {
${names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(icons[n])},`).join("\n")}
} as const;

export type ShellIcon = keyof typeof SONE_ICONS;
`;
writeFileSync(target, out);
console.log(`icons: ${names.length} glyphs → ${target}`);
